application: btcpanel
version: 1
runtime: python
api_version: 1

builtins:
  - admin_redirect: on
  - datastore_admin: on
  - appstats: on

handlers:
  - url: /api/.*
    script: src/api.py

  - url: /static/(.*)
    static_files: static/\1
    upload: /static/
  
  - url: /
    static_files: static/html/index.html
    upload: /static/
  
  - url: .*
    static_files: static/html/404.html
    upload: /static/

